name: ProjectCard Auto Labels

on:
  project_card:
    types: [moved]

jobs:
  projectcardautolabel_job:
    runs-on: ubuntu-latest
    steps:
    - name: Run ProjectCard AutoLabel
      id: runprojectcardautolabel
      uses: Matticusau/projectcard-autolabel@v1.0.0
      
      with:
        autolabel-config: >
          [
            {"column":"Resolved", "remove_labels": ["waiting-test"], "add_labels": [":heavy_check_mark: resolved"]}
          ]
        projectfilter-config: '{"include":["*"]}'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
