name: issue-automation

on:
  issues:
    types: [reopened]

jobs:
  remove-reopened-issues:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          remove-labels: "waiting-test"
